language: python
sudo: false
notifications:
    email: false
env:
    global:
        - TZ=UTC
python:
    - 3.6
install: pip install tox-travis
before_script:
    - pip install python-coveralls
script:
    - tox
    - coverage run --source=cfltools -m py.test
    - coverage report -m
after_success: coveralls


